---
# Per environment values which override defaults in hmpps-prison-roll-count/values.yaml

generic-service:
  ingress:
    host: prison-roll-count.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prison-roll-count.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: move-a-prisoner-alerts-prod
