---
# Per environment values which override defaults in hmpps-prison-roll-count/values.yaml

generic-service:
  ingress:
    host: prison-roll-count.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prison-roll-count.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"

    # APIs
    LOCATIONS_INSIDE_PRISON_API_URL: "https://locations-inside-prison-api.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk"

    # Service URLs
    CHANGE_SOMEONES_CELL_URL: "https://change-someones-cell.prison.service.justice.gov.uk"
    DIGITAL_PRISONS_URL: "https://digital.prison.service.justice.gov.uk"
    PRISONER_PROFILE_URL: "https://prisoner.digital.prison.service.justice.gov.uk"

    AUDIT_ENABLED: "false"

    TAG_MANAGER_CONTAINER_ID: "G-6RRVY5L6EF"

  generic-prometheus-alerts:
    alertSeverity: move-a-prisoner-alerts-prod
