name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "46 8 * * MON-FRI" # Every weekday
jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: move-a-prisoner-alerts
    secrets: inherit
